### ISSUE TITLE
Junior Scrum Master and Helpers Have Rough Draft of Question Survey Ready for Next Week's Scrum Meeting

### ISSUE THREAD

**Issue by gmarks-ut** [gmarks-ut/QMB210-FA24#5]

**Comment by gmarks-ut** [comment]
@nicolefdz @anacrisostomo09 @kaylynott @Evan-22 @George2195 @Justin-Tomasina @andrewa131930 @kaylynott @morgan-wimberly  @colemane22 

Just wanted to check in before tonight.  Does everyone have a rough draft created by their junior scrum master?
Also have you reviewed it with your team?

**Comment by kaylynott** [comment]
We have one, we review it tonight at 8:30

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gmarks-ut** [comment]
Great, I clicked on the link but I'm not able to open as it is going to outlook, should go to a qualtrics link.  But we can go over in the meeting

**Comment by kaylynott** [comment]
https://utampa.az1.qualtrics.com/jfe/preview/previewId/4a28fdc0-32e3-410f-9fb8-11aa16bae46d/SV_9sIxt4u9X63tVfo?Q_CHL=preview&Q_SurveyVersionID=current

**Comment by George2195** [comment]
https://utampa.az1.qualtrics.com/survey-builder/SV_6xKrP6jQxLIgl1Q/edit?Section=SV_6xKrP6jQxLIgl1Q

**Comment by morgan-wimberly** [comment]
Reviewed with team during zoom call 
Link to survey:
https://utampa.az1.qualtrics.com/survey-builder/SV_cZ82Oa2X4Kr27AO/edit

**Comment by andrewa131930** [comment]
Link to Survey:
https://qualtricsxmq3znzhfzj.az1.qualtrics.com/jfe/preview/previewId/a3f4ebe8-8a86-4589-9796-e9399616d612/SV_3ZZHBEB8Ggp7utg?Q_CHL=preview&Q_SurveyVersionID=current

**Comment by gmarks-ut** [comment]
@morgan-wimberly  When trying to review your team survey it says I do not have permission.  Can you please give me access so I can give you feedback.

**Comment by morgan-wimberly** [comment]
Yes, sorry! I think I fixed it now.

**Comment by gmarks-ut** [comment]
@morgan-wimberly   Sorry, still having issues.  Otherwise let's see if we can solve in class, or we can ask ITS desk downstairs from classs
